// app/layout.js
import "./globals.css"; // CSS 전역파일 (없으면 생성)

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head />
      <body
        style={{
          fontFamily:
            "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
          backgroundColor: "#fffefeff", // 전체 배경색
          margin: 0,
          padding: 0,
        }}
      >
        {children}
      </body>
    </html>
  );
}
